# Generated by Django 5.1.2 on 2024-10-29 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('iddisciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nombredisciplina', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disciplina',
                'ordering': ['nombredisciplina'],
            },
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('idarbitro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('primerapellido', models.CharField(max_length=50)),
                ('segundoapellido', models.CharField(max_length=50)),
                ('fechanacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1)),
                ('iddisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitros', to='AppPractica8.disciplina')),
            ],
            options={
                'db_table': 'arbitro',
                'ordering': ['nombre'],
            },
        ),
    ]
